services:
  mongodb:
    image: mongo:7
    container_name: raleigh-mongo
    command: ["--replSet", "rs0", "--bind_ip_all", "--noauth"]
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: raleigh-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data: